# Describes the format for available meural services

set_brightness:
  description: Change backlight brightness setting of the Meural frame.
  fields:
    entity_id:
      description: Entity ID of the Meural frame.
      example: "media_player.meural"
    brightness:
      description: Backlight brightness on a scale of 0 (low) to 100 (high).
      example: "90"
reset_brightness:
  description: Automatically adjust Meural frame backlight to room's lighting.
  fields:
    entity_id:
      description: Entity ID of the Meural frame.
      example: "media_player.meural"
set_device_option:
  description: Set a Meural canvas' configuration options.
  fields:
    entity_id:
      description: Entity ID of the Meural canvas to update.
      example: "media_player.meural"
    orientation:
      description: This manually changes the orientation of images on your Canvas. Can be horizontal, vertical.
      example: "horizontal" 
    orientationMatch:
      description: Your Canvas only shows works that match its current orientation, i.e. if your Canvas is in vertical, only vertical works will display. 
      example: "true"
    alsEnabled:
      description: Your Canvas can automatically adjusts its brightness to match its surroundings using the Ambient Light Sensor.
      example: "true"
    alsSensitivity:
      description: On high light sensitivity, your Canvas will pick up more light in the room, and become brighter to match. Likewise, low sensitivity will make your Canvas less bright. Default settings are 100 for High, 20 for Medium, and 4 for Low.
      example: "20"
    goesDark:
      description: When there's no light in the room, the Canvas will go into sleep mode. When the room becomes light again, the Canvas will wake up.
      example: "true"
    imageShuffle:
      description: Randomize the order that images show within an individual playlist.
      example: "false"
    imageDuration:
      description: The length of time in seconds between images. To prevent images from changing automatically, enter '0'.
      example: "300"
    previewDuration:
      description: The length of time in seconds an image previews from the mobile app.
      example: "120"
    overlayDuration:
      description: Timeout in seconds for hiding overlays such as captions, settings, and playlists.
      example: "60"
    gestureFeedback:
      description: Preview images in a playlist when changing image using gesture.
      example: "false"
    gestureFeedbackHelp:
      description: Show help text when gesturing.
      example: "true"
    gestureFlip:
      description: Invert your Canvas horizontal gestures. Applies on image rotation in a playlist and on-screen menu selections.
      example: "false"
    backgroundColor:
      description: The color behind images that don't fill the frame. Can be gray, white, black.
      example: "black"
    fillMode: 
      description: How images fill the screen if they don't match the Canvas' aspect ratio. Can be contain, auto crop, as is, stretch.
      example: "auto crop"
    galleryRotation:
      description: When a playlist reaches the last image, automatically rotate to the next playlist. A playlist won't be rotated if you manually switch from the last images to the first.
      example: "false"
    schedulerEnabled:
      description: Enable scheduler. With the Scheduler, you can put the Canvas to sleep and wake it up at certain times of day or schedule playlists at certain times.
      example: "true"