# Describes the format for available Meural services

set_brightness:
  description: Change backlight brightness setting of the Meural Canvas.
  fields:
    entity_id:
      description: Entity ID of the Meural Canvas to update.
      example: "media_player.meural-123"
    brightness:
      description: Backlight brightness on a scale of 0 (low) to 100 (high).
      example: "50"
reset_brightness:
  description: Automatically adjust Meural Canvas backlight to room's lighting according to ambient light sensor.
  fields:
    entity_id:
      description: Entity ID of the Meural Canvas to update.
      example: "media_player.meural-123"
toggle_informationcard:
  description: Toggle display of the information card, a museum-style placard, on your Canvas.
  fields:
    entity_id:
      description: Entity ID of the Meural Canvas to toggle display on.
      example: "media_player.meural-123"
synchronize:
  description: Synchronize the Meural server with your Meural Canvas.
  fields:
    entity_id:
      description: Entity ID of the Meural Canvas to synchronize.
      example: "media_player.meural-123"
preview_image:
  description: Preview an image from an URL on Meural Canvas.
  fields:
    entity_id:
      description: Entity ID of the Meural Canvas to update.
      example: "media_player.meural-123"
    content_url:
      description: URL of the image to preview.
      example: "https://home-assistant.io/images/cast/splash.png"
    content_type:
      description: The type of image to preview. Can be image/jpg or image/png.
      example: "image/png"

preview_image_cloud:
  description: Preview an image from an URL on Meural Canvas (Uses Meural cloud storage to work around the sticky image issue when displaying an image using local API).
  fields:
    entity_id:
      description: Entity ID of the Meural Canvas to update.
      example: "media_player.meural-123"
    content_url:
      description: URL of the image to preview.
      example: "https://home-assistant.io/images/cast/splash.png"
    content_type:
      description: The type of image to preview. Can be image/jpg or image/png.
      example: "image/png"
    name:
      description: Name of the media item
      example: "Game of Thrones"
    author:
      description: Author or Artist name
      example: George Martin
    description:
      description: Description for the media item
      example: Game of Thrones Poster image
    medium:
      description: Medium for the media item
      example: Photography
    year:
      description: Year. This needs to be a date or just the year. Other format doesn't work
      example: 2022/05/01

set_device_option:
  description: Set the configuration options of a Meural Canvas.
  fields:
    entity_id:
      description: Entity ID of the Meural Canvas to update.
      example: "media_player.meural-123"
    orientation:
      description: Override the orientation of images on your Canvas. Can be horizontal, vertical.
      example: "horizontal"
    orientationMatch:
      description: Your Canvas will only show images that match its current orientation, i.e. if your Canvas is in vertical, only vertical images will display.
      example: "true"
    alsEnabled:
      description: Your Canvas will automatically adjusts its brightness to match its surroundings using the Ambient Light Sensor.
      example: "true"
    alsSensitivity:
      description: Light sensitivity of your Canvas on a scale of 0 (low) to 100 (high). On high sensitivity, your Canvas will become brighter to match the light in the room. Default settings are 100 (High), 20 (Medium), and 4 (Low).
      example: "20"
    goesDark:
      description: Your Canvas will go into sleep mode when there's no light in the room. When the room becomes light again, your Canvas will wake up.
      example: "true"
    imageShuffle:
      description: Your Canvas will randomize the order of images within an individual playlist.
      example: "false"
    imageDuration:
      description: Length of time in seconds between images changing on your Canvas. To prevent images from changing automatically, enter '0'.
      example: "1800"
    previewDuration:
      description: Length of time in seconds an image previews on your Canvas from the mobile app.
      example: "60"
    overlayDuration:
      description: Length of time in seconds that overlays such as captions, settings, and playlists are displayed on your Canvas.
      example: "120"
    gestureFeedback:
      description: Your Canvas will display a preview of images in the playlist when switching image manually.
      example: "false"
    gestureFeedbackHelp:
      description: Your Canvas will show help text when displaying a preview of images in the playlist.
      example: "true"
    gestureFlip:
      description: Your Canvas will invert left/right controls. Applies on image rotation in a playlist and on-screen menu selections.
      example: "false"
    backgroundColor:
      description: Color displayed behind images that don't fill the frame. Can be grey, white, black.
      example: "black"
    fillMode:
      description: How images will fill the screen if they don't match the Canvas' aspect ratio. Can be contain, auto crop, as is, stretch.
      example: "auto crop"
    galleryRotation:
      description: Atomatically rotate to the next playlist when your Canvas reaches the last image in a playlist. Playlists won't be rotated if you manually switch from the last image to the first.
      example: "false"
    schedulerEnabled:
      description: Enable scheduler. With the scheduler, you can put your Canvas to sleep and wake it up at certain times of day or schedule playlists at certain times.
      example: "true"
